apiVersion: v1
kind: Namespace
metadata:
  name: eshoponweb-user002
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshoponweb-user002
  name: webapp
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: sample-app
        service: webapp
    spec:
      containers:
        - name: webapp
          image: aistraining.azurecr.io/eshoponweb-user002:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://webapi
